services:
  credit-card-service:
    image: wiremock/wiremock:3.3.1-1
    ports:
      - "4002:8080"
    volumes:
      - ./wiremock:/home/wiremock

  online-shop-database:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=P@55w0rd

  online-shop-migration:
    image: flyway/flyway:10.10
    command: -url=jdbc:postgresql://online-shop-database:5432/postgres -user=postgres -password=P@55w0rd -connectRetries=60 migrate
    volumes:
      - ./online-shop/src/main/resources/db:/flyway/sql
    depends_on:
      - online-shop-database

  online-shop:
    build: online-shop/
    ports:
      - "4000:8080"
    environment:
      - EXTERNAL_URL=http://localhost:4000
      - JAKARTA_PERSISTENCE_JDBC_URL=jdbc:postgresql://online-shop-database:5432/postgres
      - JAKARTA_PERSISTENCE_JDBC_USER=postgres
      - JAKARTA_PERSISTENCE_JDBC_PASSWORD=P@55w0rd

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
