version: '3'

services:
  checkout-database:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd

  checkout-service:
    build: checkout-service/
    ports:
      - "4001:8080"
    environment:
      - EXTERNAL_URL=http://localhost:4001
      - CUSTOMER_CARE_SERVICE_URL=http://customer-care-service:8080
      - CREDIT_CARD_SERVICE_URL=http://credit-card-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
      - JAKARTA_PERSISTENCE_JDBC_URL=jdbc:postgresql://checkout-database:5432/postgres
      - JAKARTA_PERSISTENCE_JDBC_USER=postgres
      - JAKARTA_PERSISTENCE_JDBC_PASSWORD=Pa55w0rd

  customer-care-service:
    build: customer-care-service/
    ports:
      - "4003:8080"
