create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create sequence SEQ_OFFER start with 1 increment by 50;
create sequence SEQ_PAYMENT start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CREDIT_CARD_PAYMENT (PAY_EXPIRY_MONTH integer, PAY_EXPIRY_YEAR integer, PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_CARD_VERIFICATION_NUMBER varchar(255), PAY_NAME varchar(255), PAY_NUMBER varchar(255), primary key (PAY_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
create table TAB_DIRECT_BILLING_PAYMENT (PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_BIC varchar(255), PAY_IBAN varchar(255), PAY_NAME varchar(255), primary key (PAY_ID));
create table TAB_EMAIL_PAYMENT (PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_EMAIL_ADDRESS varchar(255), primary key (PAY_ID));
create table TAB_OFFER (OFF_ID bigint not null, payment_PAY_ID bigint unique, OFF_BILLING_ADDRESS_CITY varchar(255), OFF_BILLING_ADDRESS_HOUSE_NUMBER varchar(255), OFF_BILLING_ADDRESS_STREET varchar(255), OFF_BILLING_ADDRESS_ZIP_CODE varchar(255), OFF_CUSTOMER_NUMBER varchar(255), OFF_DELIVERY_ADDRESS_CITY varchar(255), OFF_DELIVERY_ADDRESS_HOUSE_NUMBER varchar(255), OFF_DELIVERY_ADDRESS_STREET varchar(255), OFF_DELIVERY_ADDRESS_ZIP_CODE varchar(255), OFF_OFFER_NUMBER varchar(255), primary key (OFF_ID));
create table TAB_OFFER_ITEM (OFI_QUANTITY integer, OFI_OFF_ID bigint not null, OFI_PRODUCT_NUMBER varchar(255));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CREDIT_CARD_PAYMENT add constraint FK_ginj9wobqjk3he4y327afqjh6 foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_DIRECT_BILLING_PAYMENT add constraint FK_1hjmgsg7vsuawiy0yycwmmm0l foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_EMAIL_PAYMENT add constraint FK_ahyeby0mcq38kr521fnh19g8c foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_OFFER_ITEM add constraint FKr9smv7shtljludp7jqu155odw foreign key (OFI_OFF_ID) references TAB_OFFER;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create sequence SEQ_OFFER start with 1 increment by 50;
create sequence SEQ_PAYMENT start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CREDIT_CARD_PAYMENT (PAY_EXPIRY_MONTH integer, PAY_EXPIRY_YEAR integer, PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_CARD_VERIFICATION_NUMBER varchar(255), PAY_NAME varchar(255), PAY_NUMBER varchar(255), primary key (PAY_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
create table TAB_DIRECT_BILLING_PAYMENT (PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_BIC varchar(255), PAY_IBAN varchar(255), PAY_NAME varchar(255), primary key (PAY_ID));
create table TAB_EMAIL_PAYMENT (PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_EMAIL_ADDRESS varchar(255), primary key (PAY_ID));
create table TAB_OFFER (OFF_ID bigint not null, payment_PAY_ID bigint unique, OFF_BILLING_ADDRESS_CITY varchar(255), OFF_BILLING_ADDRESS_HOUSE_NUMBER varchar(255), OFF_BILLING_ADDRESS_STREET varchar(255), OFF_BILLING_ADDRESS_ZIP_CODE varchar(255), OFF_CUSTOMER_NUMBER varchar(255), OFF_DELIVERY_ADDRESS_CITY varchar(255), OFF_DELIVERY_ADDRESS_HOUSE_NUMBER varchar(255), OFF_DELIVERY_ADDRESS_STREET varchar(255), OFF_DELIVERY_ADDRESS_ZIP_CODE varchar(255), OFF_OFFER_NUMBER varchar(255), primary key (OFF_ID));
create table TAB_OFFER_ITEM (OFI_QUANTITY integer, OFI_OFF_ID bigint not null, OFI_PRODUCT_NUMBER varchar(255));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CREDIT_CARD_PAYMENT add constraint FK_ginj9wobqjk3he4y327afqjh6 foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_DIRECT_BILLING_PAYMENT add constraint FK_1hjmgsg7vsuawiy0yycwmmm0l foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_EMAIL_PAYMENT add constraint FK_ahyeby0mcq38kr521fnh19g8c foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_OFFER_ITEM add constraint FKr9smv7shtljludp7jqu155odw foreign key (OFI_OFF_ID) references TAB_OFFER;
create sequence SEQ_ADDRESS start with 1 increment by 50;
create sequence SEQ_CUSTOMER start with 1 increment by 50;
create sequence SEQ_OFFER start with 1 increment by 50;
create sequence SEQ_PAYMENT start with 1 increment by 50;
create table TAB_ADDRESS (ADR_CUS_ID bigint, ADR_ID bigint not null, ADR_CITY varchar(255), ADR_HOUSE_NUMBER varchar(255), ADR_STREET varchar(255), ADR_ZIP_CODE varchar(255), primary key (ADR_ID));
create table TAB_CREDIT_CARD_PAYMENT (PAY_EXPIRY_MONTH integer, PAY_EXPIRY_YEAR integer, PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_CARD_VERIFICATION_NUMBER varchar(255), PAY_NAME varchar(255), PAY_NUMBER varchar(255), primary key (PAY_ID));
create table TAB_CUSTOMER (CUS_DEFAULT_BILLING_ADR_ID bigint unique, CUS_DEFAULT_DELIVERY_ADR_ID bigint unique, CUS_ID bigint not null, CUS_CUSTOMER_NUMBER varchar(255), primary key (CUS_ID));
create table TAB_DIRECT_BILLING_PAYMENT (PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_BIC varchar(255), PAY_IBAN varchar(255), PAY_NAME varchar(255), primary key (PAY_ID));
create table TAB_EMAIL_PAYMENT (PAY_ID bigint not null, PAY_OFF_ID bigint unique, PAY_EMAIL_ADDRESS varchar(255), primary key (PAY_ID));
create table TAB_OFFER (OFF_ID bigint not null, payment_PAY_ID bigint unique, OFF_BILLING_ADDRESS_CITY varchar(255), OFF_BILLING_ADDRESS_HOUSE_NUMBER varchar(255), OFF_BILLING_ADDRESS_STREET varchar(255), OFF_BILLING_ADDRESS_ZIP_CODE varchar(255), OFF_CUSTOMER_NUMBER varchar(255), OFF_DELIVERY_ADDRESS_CITY varchar(255), OFF_DELIVERY_ADDRESS_HOUSE_NUMBER varchar(255), OFF_DELIVERY_ADDRESS_STREET varchar(255), OFF_DELIVERY_ADDRESS_ZIP_CODE varchar(255), OFF_OFFER_NUMBER varchar(255), primary key (OFF_ID));
create table TAB_OFFER_ITEM (OFI_QUANTITY integer, OFI_OFF_ID bigint not null, OFI_PRODUCT_NUMBER varchar(255));
alter table if exists TAB_ADDRESS add constraint FK4xf13n4oh1ao0ff546ykumcsk foreign key (ADR_CUS_ID) references TAB_CUSTOMER;
alter table if exists TAB_CREDIT_CARD_PAYMENT add constraint FK_ginj9wobqjk3he4y327afqjh6 foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_CUSTOMER add constraint FK2kbtevm2tgmhoanj6gtg6s2v9 foreign key (CUS_DEFAULT_BILLING_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_CUSTOMER add constraint FK4apjem60mor2rgfwirvfi1014 foreign key (CUS_DEFAULT_DELIVERY_ADR_ID) references TAB_ADDRESS;
alter table if exists TAB_DIRECT_BILLING_PAYMENT add constraint FK_1hjmgsg7vsuawiy0yycwmmm0l foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_EMAIL_PAYMENT add constraint FK_ahyeby0mcq38kr521fnh19g8c foreign key (PAY_OFF_ID) references TAB_OFFER;
alter table if exists TAB_OFFER_ITEM add constraint FKr9smv7shtljludp7jqu155odw foreign key (OFI_OFF_ID) references TAB_OFFER;
