insert into TAB_CUSTOMER (CUS_ID, CUS_CUSTOMER_NUMBER, CUS_DEFAULT_BILLING_ADR_ID, CUS_DEFAULT_DELIVERY_ADR_ID)
  values (nextval('SEQ_CUSTOMER'), '0815', null, null);
insert into TAB_ADDRESS (ADR_ID, ADR_CUS_ID, ADR_STREET, ADR_HOUSE_NUMBER, ADR_ZIP_CODE, ADR_CITY)
  values (nextval('SEQ_ADDRESS'), currval('SEQ_CUSTOMER'), 'Poststr.', '1', '26122', 'Oldenburg');
update TAB_CUSTOMER set CUS_DEFAULT_BILLING_ADR_ID = currval('SEQ_ADDRESS') WHERE CUS_CUSTOMER_NUMBER = '0815';
insert into TAB_ADDRESS (ADR_ID, ADR_CUS_ID, ADR_STREET, ADR_HOUSE_NUMBER, ADR_ZIP_CODE, ADR_CITY)
  values (nextval('SEQ_ADDRESS'), currval('SEQ_CUSTOMER'), 'II. Hagen', '7', '45127', 'Essen');
update TAB_CUSTOMER set CUS_DEFAULT_DELIVERY_ADR_ID = currval('SEQ_ADDRESS') WHERE CUS_CUSTOMER_NUMBER = '0815';
